#!/bin/bash

echo "🔍 Проверка сервера для установки Rasa Studio..."
echo "================================================"

# Проверка подключения
echo "📡 Проверка подключения к серверу..."
ping -c 3 100.111.172.61

echo ""
echo "📋 Команды для выполнения на сервере:"
echo "====================================="
echo ""
echo "1. Проверка ОС и версии:"
echo "   cat /etc/os-release"
echo "   uname -a"
echo ""
echo "2. Проверка ресурсов:"
echo "   free -h"
echo "   df -h"
echo "   nproc"
echo "   lscpu | grep 'Model name'"
echo ""
echo "3. Проверка открытых портов:"
echo "   sudo netstat -tlnp | grep -E ':(22|443|30000|30002)'"
echo ""
echo "4. Проверка DNS:"
echo "   nslookup 100.111.172.61"
echo "   hostname -f"
echo ""
echo "5. Проверка прав sudo:"
echo "   sudo -l"
echo ""
echo "6. Проверка доступного места:"
echo "   df -h /"
echo "   df -h /home"
echo ""
echo "7. Проверка версии Python (если установлен):"
echo "   python3 --version"
echo "   pip3 --version"
echo ""
echo "8. Проверка Docker (если установлен):"
echo "   docker --version"
echo "   docker-compose --version"
echo ""
echo "9. Проверка Helm (если установлен):"
echo "   helm version"
echo ""
echo "10. Проверка Kubernetes (если установлен):"
echo "    kubectl version --client"
echo ""
echo "================================================"
echo "✅ После выполнения этих команд мы сможем определить:"
echo "   - Совместимость ОС с Rasa Studio"
echo "   - Достаточность ресурсов (4 vCPU, 16GB RAM, 100GB)"
echo "   - Доступность необходимых портов"
echo "   - Наличие DNS-записи"
echo "   - Права администратора"
echo ""
echo "🚀 Готов к установке Rasa Studio!" 